version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: soozvyacheslav/foodgram_backend:latest
    build: ../backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/
  frontend:
    image: soozvyacheslav/foodgram_frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend  
  nginx:
    image: soozvyacheslav/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/